# Project 4 -- Tanay Patel

**TA Help:** (for instance) John Smith, Alice Jones, etc., list names of any TAs who helped you

- For example: Help with figuring out how to write a function (describe the tasks that they helped you with)

**Collaboration:** My Friend in CS, My Uncle, Another Student, etc., list names of any other people who helped you

(describe the tasks that they helped you with)
- For example: helped figuring out how to load the dataset.
- Another example: helped debug error with my plot.

**Internet Resources:** Stack Exchange, Stack Overflow, etc.

(describe any information that you learned from internet resources, including the URLs)
- data frames in Pandas versus R from StackOverflow  https://stackoverflow.com/questions/8991709/why-were-pandas-merges-in-python-faster-than-data-table-merges-in-r-in-2012

**ChatGPT, Gemini, Claude, etc:** Any language models or generative AI chatbots that helped you.

(if you used any such tools, please tell us here)
- For example:  I asked ChatGPT how to define a new data frames
- Another example:  Gemini told me how to make a function for sorting my data

- ***Link to AI Chat History***: Please share a link to your chat if you used AI (ex. ChatGPT Shared Links)
**OVERALL MESSAGE:** Any time that you used anything except your brain to solve the questions in these projects, you need to disclose such resources at the start of the project, with details about your usage of the tools.

**YOUR OWN WORK:** Even when you utilize other resources, do NOT just copy and paste.  Write all explanations in your own words, using several sentences in English, which are understandable and which you wrote (and did not just copy and paste).

## Question 1

In [1]:
import pandas as pd
myDF = pd.read_csv('/anvil/projects/tdm/data/titanic/titanic.csv')

In [2]:
myDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [3]:
myDF.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [4]:
my_names = myDF["Name"].tolist()
my_ages = myDF["Age"].tolist()

In [5]:
combined_list = my_names + my_ages

In [6]:
combined_list[:20]

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry',
 'Moran, Mr. James',
 'McCarthy, Mr. Timothy J',
 'Palsson, Master. Gosta Leonard',
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
 'Nasser, Mrs. Nicholas (Adele Achem)',
 'Sandstrom, Miss. Marguerite Rut',
 'Bonnell, Miss. Elizabeth',
 'Saundercock, Mr. William Henry',
 'Andersson, Mr. Anders Johan',
 'Vestrom, Miss. Hulda Amanda Adolfina',
 'Hewlett, Mrs. (Mary D Kingcome) ',
 'Rice, Master. Eugene',
 'Williams, Mr. Charles Eugene',
 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
 'Masselmani, Mrs. Fatima']

In [7]:
combined_df = myDF[["Name", "Age"]]
combined_df

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [8]:
combined_df.shape

(891, 2)

In question 1, we learn about lists in Python and then we make a list out of the Name and Age columns of the titanic dataset and make a combined list having  both names and ages. Then instead of a list, we just make a smaller dataframe containing only Name and Age columns from the titanic dataset.

## Question 2

In [9]:
my_names = myDF["Name"]
my_ages = myDF["Age"]

In [10]:
my_names.shape

(891,)

In [11]:
my_names.dtype

dtype('O')

In [12]:
myDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [13]:
my_names[44]

'Devaney, Miss. Margaret Delia'

In [14]:
my_ages[44]

np.float64(19.0)

In [15]:
my_ages[my_ages < 20]

7       2.0
9      14.0
10      4.0
14     14.0
16      2.0
       ...
855    18.0
869     4.0
875    15.0
877    19.0
887    19.0
Name: Age, Length: 164, dtype: float64

In [16]:
under20_ages = my_ages[my_ages < 20]
under20_names = my_names[my_ages < 20]

In [17]:
my_selection = my_ages < 20

In [18]:
my_result = my_names[my_selection] + ", age " + my_ages[my_selection].astype(str)
my_result

7             Palsson, Master. Gosta Leonard, age 2.0
9       Nasser, Mrs. Nicholas (Adele Achem), age 14.0
10           Sandstrom, Miss. Marguerite Rut, age 4.0
14     Vestrom, Miss. Hulda Amanda Adolfina, age 14.0
16                      Rice, Master. Eugene, age 2.0
                            ...
855              Aks, Mrs. Sam (Leah Rosen), age 18.0
869          Johnson, Master. Harold Theodor, age 4.0
875        Najib, Miss. Adele Kiamie "Jane", age 15.0
877                    Petroff, Mr. Nedelio, age 19.0
887            Graham, Miss. Margaret Edith, age 19.0
Length: 164, dtype: object

In question 2, we checked the shape, dtype, and the 45th row entry from both my_names and my_ages to understand what kind of data they contain. Then we filtered the Age values that were strictly less than 20 and used the same filter on the Name column to get the matching names. After that, we saved the under-20 filter as my_selection and used it to create my_result by pasting the filtered names with their ages in a single combined string format.

## Question 3

In [19]:
myDF["Status"] = myDF["Survived"].map({
    0: "Dead",
    1: "Alive"
})

In [20]:
myDF["Combined"] = myDF["Status"] + " | " + myDF["Sex"]

In [21]:
myDF["Status"].value_counts()

Status
Dead     549
Alive    342
Name: count, dtype: int64

In [22]:
myDF["Combined"].value_counts()

Combined
Dead | male       468
Alive | female    233
Alive | male      109
Dead | female      81
Name: count, dtype: int64

### We used the map() method to add lapeps to the Survived column

In question 3, we looked at the Survived column and created a new Status column by assigning the labels Dead and Alive to the 0 and 1 values. Then we combined this Status column with the Sex column to create a new column called Combined using a separator between the two values. Finally, we used value counts to see how the Status values and the Combined status-sex pairs are distributed in the dataset.

## Question 4

In [23]:
old_ages = [61, 62, 63, 64, 65, 66, 70, 70.5, 71, 74, 80]

In [24]:
old = myDF["Age"][myDF["Age"].isin(old_ages)]

In [25]:
myDF["Age"].min()
myDF["Age"].max()

80.0

In [26]:
old.value_counts()

Age
62.0    4
61.0    3
65.0    3
70.0    2
71.0    2
63.0    2
64.0    2
66.0    1
70.5    1
80.0    1
74.0    1
Name: count, dtype: int64

In [27]:
my_list1 = myDF["Age"][myDF["Age"] <= 10].tolist()
my_list2 = myDF["Age"][(myDF["Age"] > 10) & (myDF["Age"] <= 60)].tolist()

In [28]:
people = my_list1 + my_list2
people[20:40]

[5.0,
 8.0,
 3.0,
 7.0,
 2.0,
 0.92,
 2.0,
 3.0,
 3.0,
 1.0,
 1.0,
 3.0,
 10.0,
 4.0,
 5.0,
 0.75,
 2.0,
 9.0,
 9.0,
 2.0]

In question 4, we looked at the value counts of the Age column and chose a cut-off to define what counts as “old” by making a list of specific old_ages values. Then we used .isin() to pull the matching Age values from the dataset and saved those results as old, and displayed the value counts to see how often those ages appear. After that, we created my_list1 for ages less than or equal to 10 and my_list2 for ages greater than 10 and up to 60, and combined them together to make the list people.

## Question 5

In [29]:
children = myDF["Age"][myDF["Age"] <= 20].tolist()
young    = myDF["Age"][(myDF["Age"] > 20) & (myDF["Age"] <= 40)].tolist()
adult    = myDF["Age"][(myDF["Age"] > 40) & (myDF["Age"] <= 60)].tolist()
old      = myDF["Age"][myDF["Age"] > 60].tolist()

In [30]:
myDF["AgeGroup"] = None
myDF.loc[myDF["Age"].isin(children), "AgeGroup"] = "Children"
myDF.loc[myDF["Age"].isin(young),    "AgeGroup"] = "Young"
myDF.loc[myDF["Age"].isin(adult),    "AgeGroup"] = "Adult"
myDF.loc[myDF["Age"].isin(old),      "AgeGroup"] = "Old"

In [31]:
myDF["AgeGroup"].value_counts()

AgeGroup
Young       385
Children    179
Adult       128
Old          22
Name: count, dtype: int64

In [32]:
pd.crosstab(myDF["AgeGroup"], myDF["Combined"])

Combined  Alive | female  Alive | male  Dead | female  Dead | male
AgeGroup
Adult                 34            16             11           67
Children              53            29             24           73
Old                    3             2              0           17
Young                107            46             29          203

In question 5, we used the people list and created three more lists based on age ranges: children, young, and adult, and we also used old for ages above 60. Then we created a new column called AgeGroup and used .isin() with .loc[] to assign a label to each person’s Age based on which list their age belongs to. Finally, we displayed the value counts of AgeGroup and used pd.crosstab() to compare the combinations between AgeGroup and the Combined column.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.

https://www.purdue.edu/odos/osrr/honor-pledge/