# Project 5 -- Tanay Patel

**TA Help:** (for instance) John Smith, Alice Jones, etc., list names of any TAs who helped you

- For example: Help with figuring out how to write a function (describe the tasks that they helped you with)

**Collaboration:** My Friend in CS, My Uncle, Another Student, etc., list names of any other people who helped you

(describe the tasks that they helped you with)
- For example: helped figuring out how to load the dataset.
- Another example: helped debug error with my plot.

**Internet Resources:** Stack Exchange, Stack Overflow, etc.

(describe any information that you learned from internet resources, including the URLs)
- data frames in Pandas versus R from StackOverflow  https://stackoverflow.com/questions/8991709/why-were-pandas-merges-in-python-faster-than-data-table-merges-in-r-in-2012

**ChatGPT, Gemini, Claude, etc:** Any language models or generative AI chatbots that helped you.

(if you used any such tools, please tell us here)
- For example:  I asked ChatGPT how to define a new data frames
- Another example:  Gemini told me how to make a function for sorting my data

- ***Link to AI Chat History***: Please share a link to your chat if you used AI (ex. ChatGPT Shared Links)
**OVERALL MESSAGE:** Any time that you used anything except your brain to solve the questions in these projects, you need to disclose such resources at the start of the project, with details about your usage of the tools.

**YOUR OWN WORK:** Even when you utilize other resources, do NOT just copy and paste.  Write all explanations in your own words, using several sentences in English, which are understandable and which you wrote (and did not just copy and paste).

## Question 1

In [1]:
import pandas as pd
import polars as pl
import time

# read in the dataset using pandas
start = time.time()
pandas_df = pd.read_csv("/anvil/projects/tdm/data/flights/subset/1987.csv")
end = time.time()
print(f"Pandas read_csv took {end - start} seconds")

# read in the dataset using polars
start = time.time()
polars_df = pl.read_csv("/anvil/projects/tdm/data/flights/subset/1987.csv", null_values=["NA"])
end = time.time()
print(f"Polars read_csv took {end - start} seconds")

Pandas read_csv took 1.4198648929595947 seconds
Polars read_csv took 0.8461391925811768 seconds

In [2]:
allstar_path = "/anvil/projects/tdm/data/lahman/data/AllstarFull.csv"
col_names = ["playerID", "yearID", "gameNum", "gameID", "teamID", "lgID", "GP", "startingPos"]

start = time.time()
pandas_df = pd.read_csv(allstar_path, header=None)
pandas_df.columns = col_names
end = time.time()
print(f"Pandas Allstar read_csv took {end - start} seconds")

start = time.time()
polars_df = pl.read_csv(allstar_path, has_header=False)
polars_df.columns = col_names
end = time.time()
print(f"Polars Allstar read_csv took {end - start} seconds")

Pandas Allstar read_csv took 0.015859603881835938 seconds
Polars Allstar read_csv took 0.01442098617553711 seconds

In [3]:
pandas_df.head()

    playerID  yearID  gameNum        gameID teamID lgID  GP  startingPos
0  kalinal01    1957        0  NLS195707090    DET   AL   1          9.0
1  demaejo01    1957        0  NLS195707090    KC1   AL   0          NaN
2   grimbo01    1957        0  NLS195707090    NYA   AL   1          NaN
3  howarel01    1957        0  NLS195707090    NYA   AL   0          NaN
4   loesbi01    1957        0  NLS195707090    BAL   AL   1          NaN

In [4]:
polars_df.head()

shape: (5, 8)
┌───────────┬────────┬─────────┬──────────────┬────────┬──────┬─────┬─────────────┐
│ playerID  ┆ yearID ┆ gameNum ┆ gameID       ┆ teamID ┆ lgID ┆ GP  ┆ startingPos │
│ ---       ┆ ---    ┆ ---     ┆ ---          ┆ ---    ┆ ---  ┆ --- ┆ ---         │
│ str       ┆ i64    ┆ i64     ┆ str          ┆ str    ┆ str  ┆ i64 ┆ i64         │
╞═══════════╪════════╪═════════╪══════════════╪════════╪══════╪═════╪═════════════╡
│ kalinal01 ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ DET    ┆ AL   ┆ 1   ┆ 9           │
│ demaejo01 ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ KC1    ┆ AL   ┆ 0   ┆ null        │
│ grimbo01  ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ NYA    ┆ AL   ┆ 1   ┆ null        │
│ howarel01 ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ NYA    ┆ AL   ┆ 0   ┆ null        │
│ loesbi01  ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ BAL    ┆ AL   ┆ 1   ┆ null        │
└───────────┴────────┴─────────┴──────────────┴────────┴──────┴─────┴─────────────┘

The string entries in the pandas columns dont have any apostrophes around them meanwhile the entries in the polars columns do have them. Pandas columns have NaN values meanwhile polars columns have null values.

In question 1, we read in the 1987 Flights dataset using both Pandas and Polars and compared how long it took each library to load the data. Then we read in the All Star dataset using both Pandas and Polars by assigning the proper column names since they were not originally included. After that, we used the .head() function on both datasets to compare how the data looked when it was read in using Pandas versus Polars.

## Question 2

In [5]:
# pandas - select columns to look at
pandas_df[['playerID', 'teamID']]

       playerID teamID
0     kalinal01    DET
1     demaejo01    KC1
2      grimbo01    NYA
3     howarel01    NYA
4      loesbi01    BAL
...         ...    ...
5668  mantijo01    ARI
5669  mikolmi01    SLN
5670  musgrjo01    SDN
5671  rodonca01    SFN
5672  willide03    MIL

[5673 rows x 2 columns]

In [6]:
polars_df.select([pl.col("playerID"), pl.col("teamID")])

shape: (5_673, 2)
┌───────────┬────────┐
│ playerID  ┆ teamID │
│ ---       ┆ ---    │
│ str       ┆ str    │
╞═══════════╪════════╡
│ kalinal01 ┆ DET    │
│ demaejo01 ┆ KC1    │
│ grimbo01  ┆ NYA    │
│ howarel01 ┆ NYA    │
│ loesbi01  ┆ BAL    │
│ …         ┆ …      │
│ mantijo01 ┆ ARI    │
│ mikolmi01 ┆ SLN    │
│ musgrjo01 ┆ SDN    │
│ rodonca01 ┆ SFN    │
│ willide03 ┆ MIL    │
└───────────┴────────┘

In [7]:
philly_players_pandas = pandas_df[pandas_df['teamID'] == "PHI"]
philly_players_pandas.head()

      playerID  yearID  gameNum        gameID teamID lgID  GP  startingPos
17   simmocu01    1957        0  NLS195707090    PHI   NL   1          1.0
38   sanfoja02    1957        0  NLS195707090    PHI   NL   1          NaN
77   ashburi01    1958        0  ALS195807080    PHI   NL   0          NaN
80   farretu01    1958        0  ALS195807080    PHI   NL   1          NaN
176  conlege01    1959        1  NLS195907070    PHI   NL   0          NaN

In [8]:
philly_players_polars = polars_df.filter(pl.col("teamID") == "PHI")
philly_players_polars.head()

shape: (5, 8)
┌───────────┬────────┬─────────┬──────────────┬────────┬──────┬─────┬─────────────┐
│ playerID  ┆ yearID ┆ gameNum ┆ gameID       ┆ teamID ┆ lgID ┆ GP  ┆ startingPos │
│ ---       ┆ ---    ┆ ---     ┆ ---          ┆ ---    ┆ ---  ┆ --- ┆ ---         │
│ str       ┆ i64    ┆ i64     ┆ str          ┆ str    ┆ str  ┆ i64 ┆ i64         │
╞═══════════╪════════╪═════════╪══════════════╪════════╪══════╪═════╪═════════════╡
│ simmocu01 ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ PHI    ┆ NL   ┆ 1   ┆ 1           │
│ sanfoja02 ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ PHI    ┆ NL   ┆ 1   ┆ null        │
│ ashburi01 ┆ 1958   ┆ 0       ┆ ALS195807080 ┆ PHI    ┆ NL   ┆ 0   ┆ null        │
│ farretu01 ┆ 1958   ┆ 0       ┆ ALS195807080 ┆ PHI    ┆ NL   ┆ 1   ┆ null        │
│ conlege01 ┆ 1959   ┆ 1       ┆ NLS195907070 ┆ PHI    ┆ NL   ┆ 0   ┆ null        │
└───────────┴────────┴─────────┴──────────────┴────────┴──────┴─────┴─────────────┘

In question 2, we selected specific columns from the All Star dataset using Pandas and then used the .select() function in Polars to do the same task. Then we filtered both datasets to find the entries where the teamID was PHI using the appropriate syntax for each library. Finally, we sorted both filtered datasets by the yearID column to view the most recent player entries.

## Question 3

In Pandas, we usually filter and select columns using bracket-based indexing like df[df["col"] == value] or df[["col1", "col2"]]. In Polars, we explicitly use expressions like .filter(pl.col("col") == value) and .select(pl.col("col")), which makes the operations more structured and clear.

In [9]:
flights_2005_path = "/anvil/projects/tdm/data/flights/subset/2005.csv"
myDF = pl.read_csv(flights_2005_path, null_values=["NA"])

In [10]:
indy_flights = myDF.filter(pl.col("Origin") == "IND")

In [11]:
indy_flights_crs = indy_flights.select(pl.col("^CRS.*$"))
indy_flights_crs.head()

shape: (5, 3)
┌────────────┬────────────┬────────────────┐
│ CRSDepTime ┆ CRSArrTime ┆ CRSElapsedTime │
│ ---        ┆ ---        ┆ ---            │
│ i64        ┆ i64        ┆ i64            │
╞════════════╪════════════╪════════════════╡
│ 1602       ┆ 1614       ┆ 72             │
│ 1602       ┆ 1614       ┆ 72             │
│ 1602       ┆ 1614       ┆ 72             │
│ 1602       ┆ 1614       ┆ 72             │
│ 1602       ┆ 1614       ┆ 72             │
└────────────┴────────────┴────────────────┘

In question 3, we read in the 2005 Flights dataset using Polars and filtered the data to only include flights that originated from IND. Then we used the .select() function with a pl.col() expression to display only the columns whose names begin with CRS. This allowed us to focus on the scheduled time-related columns for the selected flights.

## Question 4

In [12]:
delay_cols = [c for c in indy_flights.columns if "Delay" in c]
len(delay_cols)

7

In [13]:
indy_flights.select(pl.col("^(Arr|Dep).*$")).head()

shape: (5, 4)
┌─────────┬─────────┬──────────┬──────────┐
│ DepTime ┆ ArrTime ┆ ArrDelay ┆ DepDelay │
│ ---     ┆ ---     ┆ ---      ┆ ---      │
│ i64     ┆ i64     ┆ i64      ┆ i64      │
╞═════════╪═════════╪══════════╪══════════╡
│ 1641    ┆ 1651    ┆ 37       ┆ 39       │
│ 1627    ┆ 1624    ┆ 10       ┆ 25       │
│ 1726    ┆ 1737    ┆ 83       ┆ 84       │
│ 1607    ┆ 1603    ┆ -11      ┆ 5        │
│ 1914    ┆ 1928    ┆ 194      ┆ 192      │
└─────────┴─────────┴──────────┴──────────┘

In [14]:
indy_flights_arr_dep_delay = indy_flights.select(pl.col("^(Arr|Dep).*Delay$"))
indy_flights_arr_dep_delay.head()

shape: (5, 2)
┌──────────┬──────────┐
│ ArrDelay ┆ DepDelay │
│ ---      ┆ ---      │
│ i64      ┆ i64      │
╞══════════╪══════════╡
│ 37       ┆ 39       │
│ 10       ┆ 25       │
│ 83       ┆ 84       │
│ -11      ┆ 5        │
│ 194      ┆ 192      │
└──────────┴──────────┘

In [15]:
indy_flights.select(pl.col("^(Arr|Dep)Delay$")).head()

shape: (5, 2)
┌──────────┬──────────┐
│ ArrDelay ┆ DepDelay │
│ ---      ┆ ---      │
│ i64      ┆ i64      │
╞══════════╪══════════╡
│ 37       ┆ 39       │
│ 10       ┆ 25       │
│ 83       ┆ 84       │
│ -11      ┆ 5        │
│ 194      ┆ 192      │
└──────────┴──────────┘

In question 4, we searched for the columns in indy_flights that contain the word Delay in their names and counted how many such columns exist. Then we selected and displayed the columns whose names begin with Arr or Dep to examine arrival and departure related information. Finally, we used a pl.col() expression to display only the ArrDelay and DepDelay columns without directly calling them by name.

## Question 5

In [16]:
myDF = myDF.with_columns(
    pl.col("ArrTime").cast(pl.Int64, strict=False)
)

In [17]:
myDF = myDF.with_columns(
    (pl.col("ArrTime") - pl.col("CRSArrTime")).abs().alias("AbsDiffArrTime")
)

In [18]:
myDF.head()

shape: (5, 30)
┌──────┬───────┬────────────┬───────────┬───┬──────────┬──────────────┬──────────────┬─────────────┐
│ Year ┆ Month ┆ DayofMonth ┆ DayOfWeek ┆ … ┆ NASDelay ┆ SecurityDela ┆ LateAircraft ┆ AbsDiffArrT │
│ ---  ┆ ---   ┆ ---        ┆ ---       ┆   ┆ ---      ┆ y            ┆ Delay        ┆ ime         │
│ i64  ┆ i64   ┆ i64        ┆ i64       ┆   ┆ i64      ┆ ---          ┆ ---          ┆ ---         │
│      ┆       ┆            ┆           ┆   ┆          ┆ i64          ┆ i64          ┆ i64         │
╞══════╪═══════╪════════════╪═══════════╪═══╪══════════╪══════════════╪══════════════╪═════════════╡
│ 2005 ┆ 1     ┆ 28         ┆ 5         ┆ … ┆ 0        ┆ 0            ┆ 0            ┆ 18          │
│ 2005 ┆ 1     ┆ 29         ┆ 6         ┆ … ┆ 0        ┆ 0            ┆ 0            ┆ 23          │
│ 2005 ┆ 1     ┆ 30         ┆ 7         ┆ … ┆ 0        ┆ 0            ┆ 0            ┆ 64          │
│ 2005 ┆ 1     ┆ 31         ┆ 1         ┆ … ┆ 0        ┆ 0            ┆ 0            ┆ 33          │
│ 2005 ┆ 1     ┆ 2          ┆ 7         ┆ … ┆ 0        ┆ 0            ┆ 0            ┆ 3           │
└──────┴───────┴────────────┴───────────┴───┴──────────┴──────────────┴──────────────┴─────────────┘

In question 5, we converted the ArrTime column to a numeric type using the .cast() function in Polars. Then we created a new column called AbsDiffArrTime by calculating the absolute difference between ArrTime and CRSArrTime. Finally, we displayed the first five rows of the updated dataset to view the newly created column along with the rest of the data.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.

https://www.purdue.edu/odos/osrr/honor-pledge/